### ISSUE TITLE
회원 테이블 설계

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/snsX#49]
**요구사항**
- 회원 테이블을 post, comment와 1:n으로 연결함

**비고**
- 회원과 post는 양방향 매핑
-  comment에서 회원으로 단방향 매핑

**Comment by greenaloud** [comment]
### Business Model
***Client***
1. Post 삭제 시 댓글도 삭제
2. 회원 탈퇴 시 Post 삭제
3. 회원 탈퇴 시 Comment 는 그대로 보관 -> 삭제된 사용자로 표시

**Comment by mtak0235** [comment]
회원 탈퇴시 comment의 정보를 변경하는것이 아니고, 해당 comment 조회 요청이 있을 시 member fk로 찾았을 때 없으면 comment의 작성자 fk를 "삭제된 사용자" memberId로 갱신.
