### ISSUE TITLE
데이터베이스 설계

### ISSUE THREAD

**Issue by mtak0235** [mtak0235/snsX#9]

**Comment by greenaloud** [comment]
![image](https://user-images.githubusercontent.com/64305493/160748532-85d7e19c-86c7-4670-97cd-10332957589b.png)

**Comment by greenaloud** [comment]
<img width="905" alt="image" src="https://user-images.githubusercontent.com/64305493/161488440-d9af698d-3363-46a5-8270-37267bd42ead.png">
